feat: add Note component
pulsate-dev/pulsate-web pull request #21
Opened 2024-07-22 01:39 UTC by Allianaab2m

## What does this PR do?
- ノートを表示する`Note`コンポーネントの実装
  - ノート本文を表示する`NoteBody`コンポーネントの実装
    - 行数が5行を超えると折りたたまれる
    - 「続きを読む」/ 「閉じる」ボタンで折り畳みの状態を切り替えできる
  - 引用元ノートを表示する`QuoteNote`コンポーネントの実装
  - (WIP) ノートへの各種アクションを起こすボタンを並べた`NoteFooter`コンポーネントの実装

## Additional Infomation
- `RenoteIcon`コンポーネントはradix-ui/iconsの類似アイコンで置き換える

2024-07-22 13:51 UTC, laminne requested changes
全体: 
NoteFooterの左端の位置をユーザーアイコンと合わせてほしいです

2024-07-22 13:51 UTC, laminne commented on app/components/QuoteNote.tsx
> +    >
mediumくらいのradiusをつけてほしいです

2024-07-23 06:30 UTC, Allianaab2m commented
レビュー頂いた箇所を修正しました．再度レビューお願いします．

2024-07-23 09:56 UTC, laminne requested changes

2024-07-28 01:42 UTC, Allianaab2m commented on app/components/NoteBody.tsx
> +          {readMore ? "閉じる" : "続きを読む"}
隠れている部分の文字数を持ってくることが難しそうなので，残り文字数表示に関しては保留させてください．
ボタンのVariantはoutlineに変更しました．

2024-07-28 12:27 UTC, laminne requested changes

2024-07-28 12:27 UTC, laminne commented on app/components/NoteBody.tsx
> +        </Button>
ボタンの上部の文字列との間隔をあけた方が良いと思います

2024-07-28 12:27 UTC, laminne commented on app/components/NoteFooter.tsx
ボタンのクリック領域が下方向にはみ出ているようなのでそこを直して欲しいです
<img width="396" alt="button area screenshot" src="https://github.com/user-attachments/assets/15a26d23-f202-498e-8383-b6c3d71ded63">

2024-07-28 12:27 UTC, laminne commented on app/components/QuotedNote.tsx
[may]
引用されているノートの位置を文字と同じ場所にしたい感じがあります
<img width="395" alt="引用リノートのスクリーンショット" src="https://github.com/user-attachments/assets/ff619fbf-e692-4f0b-98f3-0c624915af55">

2024-07-29 06:16 UTC, laminne approved these changes

2024-07-29 06:50 UTC, merged